name: Run Tests via Docker

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  docker-test:
    name: Test using Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: dzil test
        run: |
          ./docker-run sh -c "
                dzil authordeps --missing | cpanm -n;
                cpanm -nq Sys::SigAction; # temporary until release of new test image
                dzil test"
      - name: docker-test-install
        run: |
          ./docker-run sh -c "
                dzil authordeps --missing | cpanm -n;
                cpanm -nq Sys::SigAction; # temporary until release of new test image
                dzil clean && dzil build;
                cpanm -v ZMQ-FFI-*.tar.gz"
